name: Deploy layer to all regions

permissions:
  contents: read

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      latest_published_version:
        description: "Latest npm published version to rebuild corresponding layer for, e.g. 1.0.2"
        default: "1.0.2"
        required: true

  workflow_call:
    inputs:
      latest_published_version:
        type: string
        description: "Latest npm published version to rebuild latest docs for, e.g. 2.0.0, 2.0.0a1 (pre-release)"
        required: true
      pre_release:
        description: "Publishes documentation using a pre-release tag (2.0.0a1)."
        default: false
        type: boolean
        required: false

jobs:
  # Build layer by running cdk synth in layer-publisher directory and uploading cdk.out for deployment
  build-layer:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
    steps:
      - name: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "20"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: CDK build
        run: npm run cdk -w layers -- synth --context PowertoolsPackageVersion=${{ inputs.latest_published_version }} -o cdk.out
      - name: Zip output
        run: zip -r cdk.out.zip layers/cdk.out
      - name: Archive CDK artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: cdk-layer-artifact
          path: cdk.out.zip

  # Deploy layer to all regions in beta account
  deploy-beta:
    needs:
      - build-layer
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    permissions:
      id-token: write
      contents: read
    with:
      stage: "BETA"
      artifact-name: "cdk-layer-artifact"
      latest_published_version: ${{ inputs.latest_published_version }}
    secrets:
      target-account-role: ${{ secrets.AWS_LAYERS_BETA_ROLE_ARN }}

  # Deploy layer to all regions in prod account
  deploy-prod:
    needs:
      - deploy-beta
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    permissions:
      id-token: write
      contents: read
    with:
      stage: "PROD"
      artifact-name: "cdk-layer-artifact"
      latest_published_version: ${{ inputs.latest_published_version }}
    secrets:
      target-account-role: ${{ secrets.AWS_LAYERS_PROD_ROLE_ARN }}

  update_layer_arn_docs:
    needs: [deploy-prod]
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent race-condition and inconsistencies with changelog push
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: none
    steps:
      - name: Checkout repository # reusable workflows start clean, so we need to checkout again
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          ref: ${{ github.sha }}
      - name: Download CDK layer artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: cdk-layer-stack
          pattern: cdk-layer-stack-* # merge all Layer artifacts created per region earlier (reusable_deploy_layer_stack.yml; step "Save Layer ARN artifact")
          merge-multiple: true
      - name: Replace layer versions in documentation
        run: |
          ls -la cdk-layer-stack/
          ./.github/scripts/update_layer_arn.sh cdk-layer-stack
      - name: Create PR
        id: create-pr
        uses: ./.github/actions/create-pr
        with: 
          files: 'docs/index.md'
          temp_branch_prefix: 'ci-layer-docs'
          pull_request_title: 'chore(ci): update layer ARN on documentation'
          github_token: ${{ secrets.GITHUB_TOKEN }}