name: Run unit tests

# 
# PROCESS
#
# 1. Checkout code
# 2. Install dependencies & build project
# 3. Run linting
# 4. Run unit tests
#
# NOTES
# We create different jobs for different workspaces of the monorepo, since we have slightly different requirements for each.
# For example, the docs (`check-docs`), runs markdown linting, while the layer (`check-layer-publisher`), examples (`check-examples`),
# and code snippets (`check-docs-snippets`) jobs run linting and unit tests but only for the current LTS version of Node.js.
#
# For the Powertools for AWS main features (aka `packages/*`), instead we run linting and unit tests for all the supported
# versions of Node.js.
#
# Since #2938, we are in the process of improving our test suite, so we are gradually extracting the tests for each package
# from (`run-linting-check-and-unit-tests-on-utilities`) to their own job, so we can run them in parallel using the matrix
# strategy and reduce the time it takes to run the tests, as well as improve maintainer experience in case of failures.
# 
# USAGE
#
# NOTE: meant to be called by ./.github/workflows/pr-run-linting-check-and-unit-tests.yml when a PR is opened or updated,
# or by ./.github/workflows/make-release.yml when a release is made.
#

on:
  workflow_call:

permissions:
  contents: read

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        version: [18, 20]
        workspace: [
          "packages/batch",
          "packages/commons",
          "packages/jmespath",
          "packages/idempotency",
          "packages/event-handler"
        ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
        with:
          nodeVersion: ${{ matrix.version }}
      - name: Linting
        run: npm run lint -w ${{ matrix.workspace }}
      - name: Unit tests
        run: |
          npm run test:unit:coverage -w ${{ matrix.workspace }}
          npm run test:unit:types -w ${{ matrix.workspace }}
  run-linting-check-and-unit-tests-on-utilities:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        version: [18, 20]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
        with:
          nodeVersion: ${{ matrix.version }}
      - name: Run linting
        run: |
          npm run lint -w packages/logger \
            -w packages/tracer \
            -w packages/metrics \
            -w packages/parameters \
            -w packages/parser
      - name: Run unit tests
        run: |
          npm t -w packages/logger \
            -w packages/tracer \
            -w packages/metrics \
            -w packages/parameters \
            -w packages/parser
  check-examples:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        example: ["app"]
      fail-fast: false
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm t
  check-layer-publisher:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint -w layers
      - name: Run tests
        run: npm run test:unit -w layers
  check-docs-snippets:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint -w examples/snippets
  check-docs:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint:markdown
